#ifndef USTR_TYPE_ENCODING_H
#define USTR_TYPE_ENCODING_H

enum {
    UENCODING_UTF8,
    UENCODING_UTF16_LE,
    UENCODING_UTF16_BE,
    UENCODING_UTF32_LE,
    UENCODING_UTF32_BE,
    UENCODING_COUNT
};

typedef unsigned char uencoding_t;

#endif