#ifndef USTR_TYPE_ENCODING_H
#define USTR_TYPE_ENCODING_H

#include <ustr/util/name.h>

// Name

UEXPORT_NAME(UENCODING_UTF8,    "UTF-8");
UEXPORT_NAME(UENCODING_UTF16LE, "UTF-16LE");
UEXPORT_NAME(UENCODING_UTF16BE, "UTF-16BE");
UEXPORT_NAME(UENCODING_UTF32LE, "UTF-32LE");
UEXPORT_NAME(UENCODING_UTF32BE, "UTF-32BE");

// Type

enum {
    UENCODING_UTF8,
    UENCODING_UTF16LE,
    UENCODING_UTF16BE,
    UENCODING_UTF32LE,
    UENCODING_UTF32BE,
    UENCODING_COUNT
};

typedef unsigned char uencoding_t;

#endif