include(CheckTypeSize)

include(scripts/util.cmake)

set_arg_type(int8_t   INT_8_ARG_TYPE  )
set_arg_type(uint8_t  UINT_8_ARG_TYPE )
set_arg_type(int16_t  INT_16_ARG_TYPE )
set_arg_type(uint16_t UINT_16_ARG_TYPE)
set_arg_type(int32_t  INT_32_ARG_TYPE )
set_arg_type(uint32_t UINT_32_ARG_TYPE)
set_arg_type(int64_t  INT_64_ARG_TYPE )
set_arg_type(uint64_t UINT_64_ARG_TYPE)

set_arg_type(int_least8_t   INT_LEAST_8_ARG_TYPE  )
set_arg_type(uint_least8_t  UINT_LEAST_8_ARG_TYPE )
set_arg_type(int_least16_t  INT_LEAST_16_ARG_TYPE )
set_arg_type(uint_least16_t UINT_LEAST_16_ARG_TYPE)
set_arg_type(int_least32_t  INT_LEAST_32_ARG_TYPE )
set_arg_type(uint_least32_t UINT_LEAST_32_ARG_TYPE)
set_arg_type(int_least64_t  INT_LEAST_64_ARG_TYPE )
set_arg_type(uint_least64_t UINT_LEAST_64_ARG_TYPE)

set_arg_type(int_fast8_t   INT_FAST_8_ARG_TYPE  )
set_arg_type(uint_fast8_t  UINT_FAST_8_ARG_TYPE )
set_arg_type(int_fast16_t  INT_FAST_16_ARG_TYPE )
set_arg_type(uint_fast16_t UINT_FAST_16_ARG_TYPE)
set_arg_type(int_fast32_t  INT_FAST_32_ARG_TYPE )
set_arg_type(uint_fast32_t UINT_FAST_32_ARG_TYPE)
set_arg_type(int_fast64_t  INT_FAST_64_ARG_TYPE )
set_arg_type(uint_fast64_t UINT_FAST_64_ARG_TYPE)